### ISSUE TITLE
8.24.02 en 8.24.03

### ISSUE THREAD

**Issue by Frans-Hut** [MinBZK/Baseline-Informatiebeveiliging-Overheid#120]
Die twee zijn dubbelop.
Wie gaat voor als ze verschillend adviseren?
De impact kan direct voelbaar worden als bv oudere smartphones van burgers niet meer bij de gemeentesite kunnen.
Toegankelijkheid voor burgers heeft ook waarde.

**Comment by dvebzk** [comment]
Dubbeling met #47
Commentaar overgenomen in ander issue.
