### ISSUE TITLE
BIO2 inleiding – Transparantie en verantwoording

### ISSUE THREAD

**Issue by jbeljonoss** [MinBZK/Baseline-Informatiebeveiliging-Overheid#127]
https://github.com/MinBZK/Baseline-Informatiebeveiliging-Overheid/blob/main/docs/inleiding/index.md#transparantie-en-verantwoording

Actuele tekst: “*Een voorbeeld van een Verklaring van Toepasselijkheid is opgenomen in de BIO2 [moet ontwikkeld worden].*”

BIOv1 heeft het over een In Control Verklaring (paragraaf 4.4). Gaat het hier om een andere naam, maar vergelijkbare doel/invulling? Een in-/externe dienstenleverancier geeft middels een rapportage inzicht in welke controls/maatregelen die hanteert, en idealiter ook inzicht in de mate van implementatie. Anders gezegd: alleen dat hij iets doet; of ook (de vindplaats van) hoe.
En is dat iets waar we middels de BIO naartoe willen, intern compliancy aan kunnen tonen?

**Comment by dvebzk** [comment]
Sluit aan op issue #30 
Commentaar overgenomen in ander issue.
