### ISSUE TITLE
Ontbreken Concepttekst om op te kunnen reageren

### ISSUE THREAD

**Issue by floort** [MinBZK/Baseline-Informatiebeveiliging-Overheid#17]
**Samenvatting**
Op [de website van de BIO](https://bio-overheid.nl/nieuws/uitgelicht-content/?article=Denk%20mee%20over%20het%20ontwerp%20van%20de%20BIO2!) staat aangekondigd dat we van 8 mei tot en met 7 juni feedback kunnen geven. Het is nu 30 mei en er is daarom nog een ruime week om feedback te geven. Maar een concept-tekst om feedback op te geven ontbreekt nog. Hoeveel tijd voor het eind van 7 juni komt de concept-tekst beschikbaar om op te reageren? Of zijn er plannen om de deadline om feedback te geven uit te stellen?

**Voorgestelde oplossing**
Concept-versie BIO2 opnemen in deze repository en/of de deadline om feedback te geven uit stellen.
 
**Alternatieven overwogen**
Feedback kan ook gebaseerd worden op BIO1, maar mist daarmee de kans om feedback te geven op de aspecten waarin de BIO1 en 2 van elkaar verschillen.

**Comment by dvebzk** [comment]
@floort: Klopt. De concepttekst is later gepubliceerd dan gepland. 
De inleiding is gisteren gepubliceerd. De maatregelen verwachten we in de loop van volgende week te publiceren (week 24).

De deadline om feedback te geven stellen we daarom uit naar 25 juli.

**Comment by floort** [comment]
Dankjewel. Prima oplossing.

**Comment by RoelBrandDeurne** [comment]
Dat is fijn! Dat heeft de ruimte om er nog goed naar te kijken.

**Comment by dvebzk** [comment]
Teksten voor de maatregelen zijn gepubliceerd met commit 0bc024a. Deadline is genoemd in de README met commit 31e12e0.
