### ISSUE TITLE
Paragraaf ontwerp

### ISSUE THREAD

**Issue by CISOMeppel** [MinBZK/Baseline-Informatiebeveiliging-Overheid#19]
Samenvatting, Doel beschrijving is vreemd verwoord

Huidige tekst
De BIO2 is een verplicht kader om de informatiebeveiliging van informatie(systemen) bij alle bestuurslagen en bestuursorganen van de overheid te bevorderen. Invulling daarvan is op basis van risicobeoordeling. Met de BIO2 draagt de overheid bij aan één gezamenlijke taal en een gemeenschappelijk doel voor een basisniveau informatiebeveiliging van de overheid.

Voorstel tekst
De BIO2 is een verplicht kader om de beveiliging van informatie(systemen) in alle bestuurslagen en bestuursorganen van de overheid te garanderen. Uitvoering geven aan de BIO is ten alle tijde gebaseerd op een grondige analyse van alle gerelatyeerde  risico's.  Met de BIO2 is er één kader voor de informatiebeveiliging binnen de overheid.

**Comment by dvebzk** [comment]
@CISOMeppel Dank voor jouw aanscherping. De inleiding is gisteren beschikbaar gekomen en is te vinden via [de BIO pagina](https://minbzk.github.io/Baseline-Informatiebeveiliging-Overheid/inleiding/). In de nieuwe tekst is jouw feedback verwerkt.
