### ISSUE TITLE
Inleiding piramidaal opbouwen

### ISSUE THREAD

**Issue by Annemieke-CIP** [MinBZK/Baseline-Informatiebeveiliging-Overheid#20]
Schrijf piramidaal, vanuit lezersvragen, met de hoofdvraag/-stelling als eerste per kop en daarna de resterende lezersvragen. Bouw alle koppen op dezelfde manier op. 
Schrijf alle tekst kort, bondig en in de actieve vorm. 
Dit komt de efficiëntie, begrijpelijkheid, snelle consumptie ten goede.

**Comment by Annemieke-CIP** [comment]
Noteer onder het doel alleen het doel. Haal de wat eruit. Noteer ze in vier bullets in mate van belangrijkheid. Dit leest voor de gebruiker prettiger dan dat de informatie op verschillende plekken staat

**Comment by dvebzk** [comment]
@Annemieke-CIP: Dankjewel voor je inbreng. In een nieuwe versie zullen we de teksten weer doorlopen op stijl. Voor wat betreft de opbouw: de huidige tekst is tot stand gekomen na een brede afstemming in de werkgroep BIO. Mochten er specifieke tekstvoorstellen zijn, laat het weten!

**Comment by Annemieke-CIP** [comment]
Specifieke tekstvoorstellen zijn separaat toegevoegd.

**Comment by BartL-CIP** [comment]
Bedankt voor deze signalen — en onze excuses voor de late terugkoppeling. De issues over schrijfstijl, terminologie en conventies zijn gebundeld en worden als pakket behandeld. De kern is al in gang gezet: de Schrijfwijzer BIO en de Structuurwijzer BIO, die de conventies vastleggen, zijn in concept. We zijn voornemens de conventies gefaseerd toe te passen bij elke volgende nieuwe versie van de BIO. Het uniformeren van termgebruik (#26) heeft daarbij prioriteit, vanwege de relatie met de Cyberbeveiligingsregeling. We sluiten de individuele issues af en verwijzen naar dit gebundelde traject via #26.
