### ISSUE TITLE
Kop Reikwijdte

### ISSUE THREAD

**Issue by Annemieke-CIP** [MinBZK/Baseline-Informatiebeveiliging-Overheid#22]
**Reikwijdte -> Organisatorische reikwijdte**
Deze tekst heeft toelichting voor de lezer nodig. Zorgplicht valt voor de lezer uit de lucht. NIS2-valt uit de lucht. Niet elke lezer heeft niet alle achtergrondinformatie die wij wel al hebben. Haal dubbele informatie eruit.

**Comment by dvebzk** [comment]
@Annemieke-CIP: dank voor je toevoeging.
De tekst van het ontwerp is niet bedoeld als zelfstandig communicatiedocument, maar als ontwerpdocument voor experts van informatiebeveiliging. Op [deze pagina](https://minbzk.github.io/Baseline-Informatiebeveiliging-Overheid/ontwerp/nis2enbio/) wordt de link met NIS2 toegelicht. 
Is de tekst uit de [Inleiding](https://minbzk.github.io/Baseline-Informatiebeveiliging-Overheid/inleiding/) wel voldoende duidelijk?

**Comment by Annemieke-CIP** [comment]
Achtergrond van mijn vraag:
- Niet iedereen in het vakgebied heeft hetzelfde kennisniveau. 
We hebben met juniors te maken, maar ook met collega's die informatiebeveiliging er maar even bij moeten doen. 
De tekst wil je leesbaar hebben voor elke gebruiker.

- Daarnaast hebben we anno 2024 te maken met een overvloed aan informatie. De manier waarop we omgaan met teksten is de laatste 25 jaar sterk veranderd. Tegenwoordige lezers lezer haastig en scannend. 

Vandaar de twee verzoeken:

1. Aangeven waar zorgplicht vandaan komt
2. Alle dubbele informatie verwijderen

**Comment by Annemieke-CIP** [comment]
De inleiding heb ik nog niet gereviewd. 
Ga ik voor je doen.
