### ISSUE TITLE
Kop Verplichtingen

### ISSUE THREAD

**Issue by Annemieke-CIP** [MinBZK/Baseline-Informatiebeveiliging-Overheid#24]
**Verplichtingen**
De eerste zin is een ander type verplichting dan de navolgende verplichtingen. De navolgende kun je besluiten om ze te wijzigen. De eerste niet. Dat is een besluit/feit. Waarom zou je de eerste verplichting opnemen?

De vierde bullet kan worden verwerkt in de derde bullet. Deze informatie staat daar als grotendeels.

**Comment by dvebzk** [comment]
In de [inleiding](https://minbzk.github.io/Baseline-Informatiebeveiliging-Overheid/inleiding/) staat de tekst zoals deze in het concept voor de BIO is geformuleerd. Voor de formulering wordt nu zoveel mogelijk de tekst aangehouden uit de lijst met Open standaarden van Forum Standaardisatie.

**Comment by Annemieke-CIP** [comment]
Dank je voor de toelichting waar de tekst vandaan komt.

Kan het uitgangspunt worden: tekst overnemen, tenzij het de begrijpelijkheid/duidelijkheid niet ten goede komt?
Hiermee kan je een verbeterloop voor andere partijen op gang krijgen.
Bijvoorbeeld ISO neemt zaken over uit de NEN 7510 waarop dit document vooruitloopt.
