### ISSUE TITLE
Kop Elementen BIO2

### ISSUE THREAD

**Issue by Annemieke-CIP** [MinBZK/Baseline-Informatiebeveiliging-Overheid#25]
**Elementen BIO2 -> Elementen**
Niet alle opgesomde elementen staan in de Harmonized Structure.

Verander de deelzin: 'Het conceptontwerp van de BIO2 omvat, conform de Harmonized Structure bevat de volgende elementen' als volgt: 'Het conceptontwerp van de BIO2 volgt de Harmonized Structure en bevat zodoende de volgende elementen'. In de originele zin kan de vraag opleveren waar Harmonized Structure vandaan komt. Licht eventueel toe waarom je deze structuur gebruikt.

Niet iedereen kent dit plug in-model. Met de aanpassing van de voorgaande zin kan in de inleiding de verwijzing naar de NEN 7510 eruit. Dit is niet relevant. Je geeft al aan de Harmonized Structure te volgen.

Tekstvoorstel tweede bullet: 'De BIO verwijst naar de verplichte eisen uit de NEN-EN-ISO 27001.

Bullet 'Verplichte overheidsspecifieke beheersmaatregelen en implementatierichtlijnen'. Ik neem aan dat je bedoeld de overheidsmaatregelen. Houd de term overheidsmaatregelen aan uit de huidige BIO. De controls uit de BIO zijn gelijk aan beheersmaatregelen in de ISO 27002. Overheidsmaatregelen uit de BIO heten implementatierichtlijnen in de ISO 27002. In het kern-IBO is besloten om de termen Controls en Overheidsmaatregelen aan te houden, vanwege de beheerlast die de wijzigingen in termen met zich mee zal brengen. Deze termen zijn reeds ingeburgerd.
Verander de deelzin: 'Dit volgt uit de context die geldt voor de overheid' in 'Dit volgt uit de risicoanalyse voor de overheid'. Hoe weet je anders welke overheidsmaatregelen er wel of niet toegevoegd moeten worden.

**Comment by dvebzk** [comment]
De samenhang met de HS zal in een volgende versie verduidelijkt worden in #26 .
