### ISSUE TITLE
Paragraaf Concept ontwerp BIO2 > Reikwijdte

### ISSUE THREAD

**Issue by RoelBrandDeurne** [MinBZK/Baseline-Informatiebeveiliging-Overheid#32]
**Over de paragraaf onder de kop Concept ontwerp BIO2 > Reikwijdte**
1. Het lijkt me niet verstandig om in de BIO2 op te nemen wanneer een organisatie een 'essentiële entiteit' is. Dat wordt in de Cyberbeveiligingswet bepaald en hoeft hier niet herhaald te worden.
2. Ik denk niet dat in de BIO2 bepaald kan worden dat overheidsorganisaties verplicht aan de BIO2 moeten voldoen als invulling van de zorgplicht. Dat zal volgens mij elders bij wet moet worden bepaald. Wel kan in de BIO2 worden opgeschreven dat de BIO2 hiervoor bedoeld is. 
3. "Als invulling *aan*:  is grammaticaal onjuist. Het moet "Als invulling *van*" zijn.
4. "Het is belangrijk dat de BIO2 ruimte geeft ..." past als formulering niet onder de kop Reikwijdte. Dat mag meer "stellend" worden verwoord. 
5. De manier waarop de NEN 7510 en CSERT worden aangehaakt vind ik niet zo gelukkig. Ze komen uit de luchtvallen zonder dat de relatie met de andere bouwstenen van de BIO2 duidelijk wordt.
6. In de laatste zin wordt geschreven over "maatregelen uit de BIO2". Ik dacht dat dat richtlijnen zouden worden genoemd.

**Voorgestelde wijziging**
De BIO2 is bedoeld voor organisaties binnen de sector overheid om invulling te geven aan de zorgplicht die volgt uit de Cyberbeveiligingswet. 

De BIO2 combineert een managementsysteem voor informatiebeveiliging volgens de norm NEN-ISO/IEC 27001 met minimale richtlijnen voor overheidsspecifieke beheersmaatregelen. Deze kunnen worden aangevuld met richtlijnen voor specifieke omgevingen zoals de NEN 7510 voor zorginformatie en de CSERT voor operationele technologie (OT). Daarmee is de BIO2 gericht op de beheersing van informatiebeveiliging in alle soorten informatie(systemen), zowel digitaal als fysiek, van alle soorten gegevens, waaronder ook persoonsgegevens en zorginformatie in alle typen omgevingen waarmee overheidsorganisaties te maken hebben.

Richtlijnen voor overheidsmaatregelen uit de BIO2 kunnen verder gebruikt worden om, waar relevant, door een overheidsorganisatie als eis[2](https://minbzk.github.io/Baseline-Informatiebeveiliging-Overheid/ontwerp/#fn:2) worden gesteld aan leveranciers en partners.

**Impact van de wijziging**
Door deze formulering is helder waarvoor de BIO2 bestemd is. (Niet waarvoor de BIO2 verplicht is. Dat wordt elders wettelijk bepaald.)

**Aanvullende informatie**
N.v.t.

**Comment by RoelBrandDeurne** [comment]
... of zal het hele hoofdstuk "Concept ontwerp BIO2" straks vervallen in de uiteindelijke tekst en worden vervangen door het hoofdstuk "BIO2 inleiding" en is mijn feedback op dat hoofdstuk dus irrelevant?

**Comment by dvebzk** [comment]
Het concept ontwerp vormt de uitgangspunten die verder zijn uitgewerkt in de inleiding en maatregelen. De tekst in de BIO inleiding is inderdaad voorzien als onderdeel van de BIO2.
