### ISSUE TITLE
Overheidsmaatregelen - BIO-wijzigingsverzoeken

### ISSUE THREAD

**Issue by Annemieke-CIP** [MinBZK/Baseline-Informatiebeveiliging-Overheid#41]
Waar kan de indiener van BIO-wijzigingsverzoeken zien, wat daarmee is gebeurd?
Het gaat om alle verzoeken die niet zijn behandeld in de werkgroep BIO, maar die in de consultatie beoordeeld zouden worden. 
Denk bijvoorbeeld aan de punt vervangen door een schuine streep, om het verschil in control-nummer en maatregel-nummer te duiden 5.01.01 versus 5.01/0.1.

**Comment by dvebzk** [comment]
De terugkoppeling van de wijzigingsverzoeken zal niet plaatsvinden via Github en zal via de BIO werkgroep verlopen.

**Comment by Annemieke-CIP** [comment]
De afspraak is dat de resterende niet behandelde BIO-wijzigingsverzoeken door de schrijvers van de BIO2 worden meegenomen. Zie het betreffende verslag van de werkgroep BIO.

Welke verzoeken zijn wel of niet verwerkt in de BIO2 met welke reden? 
Zodat deze informatie op de BIO-website kan worden toegevoegd.
Als we dit niet doen, loop je de kans dat er geen BIO-wijzigingsverzoeken meer worden ingediend. Goodwill raak je kwijt.

**Comment by dvebzk** [comment]
Zoals aangegeven zal dit in de werkgroep worden besproken en natuurlijk worden terugkoppeld aan de indieners.
Het concept op Github is een tussentijdse versie. Er is geen sprake van dat er een definitief besluit is genomen om de wijzigingen wel of niet te verwerken. Dat valt pas te zeggen na vaststelling door de werkgroep. zoals ook in de disclaimer is aangegeven: "Dit is een werkversie van de BIO2. De teksten zijn nog niet representatief voor de definitieve versie. De documentatie is alleen bedoeld om mee te kunnen denken. De definitieve versie kan nog wezenlijk veranderen."
