### ISSUE TITLE
Verduidelijking CVD uitleg 

### ISSUE THREAD

**Issue by floort** [MinBZK/Baseline-Informatiebeveiliging-Overheid#5]
**Samenvatting**
De tekst in de 2.0 opmaat specificeert niet expliciet waaraan een CVD beleid moet voldoen.

**Achtergrond**
Relatief veel organisaties hebben geen echt CVD beleid maar noemen het wel zo. Het komt relatief vaak voor dat organisaties alleen meldingen accepteren als de melders een potentieel onbeperkte geheimhouding beloven terwijl de disclosure het uitgangspunt is van CVD om zo breed mogelijk te kunnen leren van elkaars fouten. Meer expliciete uitleg over wat CVD beleid betekent helpt hopelijk.

**Voorgestelde oplossing**
Vervang bij maatregel 5.24 kolom Overheidsmaatregel de tekst "Een Coordinated Vulnerability Disclosure (CVD)-procedure is gepubliceerd en ingericht, inclusief de opvolging 46)." met "Een Coordinated Vulnerability Disclosure (CVD)-procedure is gepubliceerd en ingericht conform de NCSC leidraad of ISO/IEC 29147:2018."

**Alternatieven overwogen**
Om de tekst beknopt te houden denk ik dat een verwijzing naar externe uitleg beter is dan de details in de tekst herhalen.

**Aanvullende context**
Zodra er concept-teksten beschikbaar zijn in de repository dien ik graag een PR in.

**Comment by dvebzk** [comment]
@floort: dankjewel voor de opmerking. We werken op dit moment aan het publiceerbaar maken van de conceptbeschrijving van de maatregelen. 
We zullen proberen om jouw voorgestelde oplossing al op te nemen in de nieuwe concepttekst.

**Comment by floort** [comment]
Bedankt. Ik houd het in de gaten!

**Comment by dvebzk** [comment]
Zie: https://minbzk.github.io/Baseline-Informatiebeveiliging-Overheid/maatregelen/#52405-een-coordinated-vulnerability-disclosure-cvd-procedure-is-gepubliceerd-en-ingericht-conform-de-ncsc-leidraad-of-isoiec-291472018-informatie-afkomstig-uit-de-coordinated-vulnerability-disclosure-cvd-meldingen-is-onderdeel-van-de-incidentrapportage

**Comment by floort** [comment]
Mooi. Bedankt. Voor de herleidbaarheid gaat het om commit 0bc024a1471361678059c1f5a9d998194509c116.
