### ISSUE TITLE
Add quickstart for non-GitHub users

### ISSUE THREAD

**Issue by bwbroersma** [MinBZK/Baseline-Informatiebeveiliging-Overheid#8]
Add quickstart to README

**Comment by dvebzk** [comment]
@bwbroersma: bedoel je dat je een algemene toelichting op Github verwacht, zoals https://docs.github.com/en/get-started/start-your-journey/git-and-github-learning-resources 
Of bedoel je een aanvulling op https://github.com/MinBZK/Baseline-Informatiebeveiliging-Overheid/blob/main/CONTRIBUTING.md

**Comment by VeridisEst** [comment]
Misschien wordt er een manier bedoeld om makkelijk mee te lezen? Nu alle work-in-progress docs doorklikken en lezen is niet per se intuitief als je github niet gewend bent en een mkdocs document compilen is ook niet zo makkelijk als een word document openen.

Misschien een webserver of github site die live een mkdocs compiled site host waar meegelezen kan worden met de 'huidige versie van het eindproduct'?

**Comment by RoelBrandDeurne** [comment]
Ik zou als CISO van een gemeente graag mee willen lezen en misschien vind ik iets en neem ik dan de moeite om te leren hoe ik een issue kan indienen. Maar ik haak nu af omdat ik na 15 minute rond klikken en stukjes lezen zelfs nog niet ontdekt heb waar ik delen van de concept tekst BIO2.0 kan lezen. 

Ik wil niet leren hoe Github werkt en hoe ik het opgestelde concept BIO document eruit kan downloaden (iets met pull?)
Daarvoor heb ik het te druk. Ik wil gewoon eenvoudig kunnen lezen. En als ik dan iets belangrijks denkt te vinden, wil ik nog wel een instructie volgen om issue in te dienen.

Maar nu is het te ingewikkeld en ben je me kwijt. Ik ga zo niet bijdragen. De opstartkosten zijn gewoon te hoog.

**Comment by VeridisEst** [comment]
Precies, @RoelBrandDeurne dat is wat ik bedoel. Als we een manier maken om gewoon 'mee te lezen' met een huidige versie van het einddocument maakt dat een stuk makkelijker.

Er zijn veel mensen die niet weten hoe markdown en mappenstructuren werken, dus dat begrijp ik volledig.

Voor nu:  onder het tabblad <>Code staat een mapje met de titel 'docs'. Daar staan de individuele tekstdocumenten die de basis gaan vormen van de BIO2. 
En leren hoe je een issue kan indienen met daarin suggesties heb je volgens mij inmiddels onder de knie ;)

**Comment by RoelBrandDeurne** [comment]
@VeridisEst Ik heb alle .md documenten doorgeklikt denk ik. Klopt dan mijn conclusie dat er nu eigenlijk nog niets te lezen is, behalve een stukje inleiding? [Op deze plaatst](https://github.com/MinBZK/Baseline-Informatiebeveiliging-Overheid/blob/main/docs/index.md) staat dat er een Conceptontwerp en de Verhouding tussen NIS en BIO beschikbaar moeten zijn. Maar die vind ik nog nergens.

**Comment by VeridisEst** [comment]
@RoelBrandDeurne volgens mij is dat een logische conclusie. De inhoudelijke staat er nog niet - zoals ook in de leeswijzer staat. De informatie over NIS2 en BIO is te vinden op /docs/ontwerp/nis2enbio.md , maar is nog niet heel uitgebreid.

**Comment by dvebzk** [comment]
@VeridisEst en @RoelBrandDeurne en @bwbroersma: De vereenvoudige weergave is nu te vinden op Github Pages via: https://minbzk.github.io/Baseline-Informatiebeveiliging-Overheid/

**Comment by VeridisEst** [comment]
@dvebzk yes! Precies wat volgens mij de wens was, mooi werk!

**Comment by RoelBrandDeurne** [comment]
Geweldig zo. Bedankt!

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: David van Es ***@***.***>
Verzonden: Wednesday, May 15, 2024 4:45:02 PM
Aan: MinBZK/Baseline-Informatiebeveiliging-Overheid ***@***.***>
CC: Roel Brand ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MinBZK/Baseline-Informatiebeveiliging-Overheid] Add quickstart for non-GitHub users (Issue #8)


Closed #8<https://github.com/MinBZK/Baseline-Informatiebeveiliging-Overheid/issues/8> as completed.

**Comment by bwbroersma** [comment]
@dvebzk: Ik had dinsdag iets te snel 2 issues aangemaakt volgens mij, ik doelde vooral op [CONTRIBUTING.md](https://github.com/MinBZK/Baseline-Informatiebeveiliging-Overheid/blob/main/CONTRIBUTING.md), het is een mooie opsplitsing maar luie mensen verwachten meer in de README.

M'n andere issue:
- #7 

doelde ik op auto-testing en deploy van de Markdown, misschien werkt daar ook al meer van dan ik dacht.

**Comment by VeridisEst** [comment]
@bwbroersma die auto testing en deploy is er nu in de vorm van de website, toch?
