### ISSUE TITLE
Inleiding - Continue ontwikkeling

### ISSUE THREAD

**Issue by Annemieke-CIP** [MinBZK/Baseline-Informatiebeveiliging-Overheid#88]
Huidige zin:
Informatiebeveiliging is een cyclisch proces, het toepassen van de BIO kan niet afgedaan worden met een eenmalig project.

Voorgestelde zinnen:
Informatiebeveiliging is een cyclisch proces. Het toepassen van de BIO is geen eenmalig project.

**Comment by dvebzk** [comment]
Zal worden meegenomen in de behandeling van #33.
