### ISSUE TITLE
Reikwijdte

### ISSUE THREAD

**Issue by PSSkyu** [MinBZK/Baseline-Informatiebeveiliging-Overheid#9]
**Beschrijf de bug**
Bij [Reikwijdte](https://github.com/MinBZK/Baseline-Informatiebeveiliging-Overheid/blob/main/docs/ontwerp/index.md#reikwijdte) staat de volgende tekst:
_De maatregelen uit de BIO2 kunnen ook gebruikt worden om, waar relevant, door een overheidorganisatie als eis[2] worden gesteld aan leveranciers en partners._

**Voorgestelde wijziging**
Schrappen van de tekst.
De eisen die gesteld kunnen worden aan leveranciers en partners moeten volgen uit risicomanagement en leveranciersmanagement.

**Impact van de wijziging**
Risicomanagement is leidend voor de stelling van eisen i.p.v. het maar uitvragen van een BIO of ISO certificering.
De voetnoot geeft het ook al weer: Toelichting: _Het gaat hier om het stellen van de BIO als een verplicht normenkader. Aanvullend kan het ook nodig zijn om specifieke maatregelen te laten volgen uit de risicoanalyse die past bij de dienst of product van de leverancier en/of het vereisen van specifieke beveiligingsdiensten door de leverancier, zoals monitoring. De BIO geeft geen invulling aan specifieke situaties._

**Aanvullende informatie**
Met de BIO 1.0 was het gangbaar om het normenkader van leveranciers te vereisen als "certificering", wat in essentie niet mogelijk is/was maar ook de risicomanagement gedachte teniet doet, want de basis is voldoende... Afhankelijk van het proces/dienst is meer of minder nodig.

**Comment by dvebzk** [comment]
@PSSkyu Dankjewel voor jouw inbreng. De inleiding is gisteren beschikbaar gekomen en is te vinden via [de BIO pagina](https://minbzk.github.io/Baseline-Informatiebeveiliging-Overheid/inleiding/). In de nieuwe tekst is jouw feedback verwerkt.

Ik hoor graag hoe jij kijkt naar de verwerking van jouw feedback.

**Comment by PSSkyu** [comment]
Bedankt, zoals nu beschreven kan ik me beter in vinden.
