### ISSUE TITLE
Inleiding - Transparantie 

### ISSUE THREAD

**Issue by Annemieke-CIP** [MinBZK/Baseline-Informatiebeveiliging-Overheid#90]
In de eerste alinea geef je aan dat de overheid transparant is over de inrichting en de staat van informatieveiligheid. 
In de derde alinea staat: het publiceren van deze documenten wordt daarom aangeraden.

-> als je aanraadt om te publiceren, hoef je dat niet te doen. Doe je dat niet, dan ben je dus ook niet transparant. Alinea 1 en 3 sluiten daarom niet op elkaar aan. 
-> Alinea een, twee en drie sluiten niet logisch op elkaar aan. Schrijf piramidaal. 
-> Dit roept vragen bij de lezer/gebruiker op.
-> Welke lezersvraag wil je hier behandelen?

**Comment by dvebzk** [comment]
Dubbeling met issue #33.
